### PR TITLE
Add Rahul Goel

### PR DESCRIPTION
**Pull request by tas50**
Rahul Goel is the manager of the Chef Infra Client now. Move BTM to alums.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Review by bennyvasquez — APPROVED** [review]
Looks good to me!

**Comment by bennyvasquez** [comment]
@btm / @rahulgoel1 can you please confirm?

**Comment by rahulgoel1** [comment]
I think this PR can be closed without a merge.

**Comment by tas50** [comment]
Merging this as it's correct today.

**Pull request merged**
