### PR TITLE
add the Supermarket project/team

### PR DESCRIPTION
**Pull request by robbkidd**
Adding the Supermarket project/team to the mix.

supermarket team dancing in the aisles

### CODE REVIEW

**Comment by robbkidd** [comment]
@jonsmorrow @krasnow @tyler-ball @marcparadise @teknofire Do you agree?

@nellshamrell I assume you've got too much else going on to be listed in here, but I'd be happy to put you back in.

@jtimberman @joshbrand @mivok Do ye Ops folk want to be listed in this at all? (Because y'all are currently members of @chef/supermarket-maintainers.)

**Comment by nellshamrell** [comment]
This looks fantastic, no need to put me back in :)

**Comment by robbkidd** [comment]
Ops folk reported out of band that they do not need to be listed here. They'll have admin access to the repo still via other means.

we are your overlords

**Comment by tas50** [comment]
Once we merge this we can rename the stuff

**Pull request merged**
