### PR TITLE
Add guidance for saying no

### PR DESCRIPTION
**Pull request by nellshamrell**
## Description
Saying no on an issue or a pull request is something that brings out a lot of FUD - this adds in a guide and some templates to use in these situations.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ x ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by jakauppila** [comment]
What is the stance on locking issues/PRs when closed for one of the reasons mentioned?

I have seen projects where something is closed yet many people come by after the fact requesting the same thing which can't happen if the issue/PR is locked after closing. Most of the reasons defined is fine to just to have someone pick up the torch and keep it moving, but what about the `Pull Request is not right for the project at this time`?

Is there anything to differentiate `not right for the project at this time` vs `we have X to do first before we can consider this, but that may take X years` ?

**Comment by nellshamrell** [comment]
@jakauppila - that is an excellent question!

For me [locking an issue](https://help.github.com/en/articles/locking-conversations) is something I would use in situations where:
* someone is trolling on the issue or PR through comments (I've seen it happen)
* when a conversation is not constructive (after a warning)
* if an issue or pull request is continually re-opened without a valid reason (i.e. information has been added to an issue or a change requests have been addressed in a pull request).

**Comment by nellshamrell** [comment]
As for

```
Is there anything to differentiate not right for the project at this time vs we have X to do first before we can consider this, but that may take X years ?
```

I think anything that depends on something happening more than a year out should be closed. There will still be a record of it - but it's so likely that project priorities and business priorities will change in the meantime that I think it's fine if it's archived as a closed issue rather than kept around as an open one.

**Comment by jakauppila** [comment]
Sure and in most instances that makes sense.

The only part I'd be concerned about is when something is said 'no' to only due to priorities within the next year, but then locked due to inactivity via the lock bot used in many Chef repos.

Is there something that could keep such scenarios closed but prevented from getting locked due to inactivity? Or is the expectation to open a new issue/PR in the future when it could potentially get picked up again? For ease of use, I think it would be beneficial to continue the discussion in the same thread.

**Comment by nellshamrell** [comment]
Good question! I'm doing some investigation on the lock bot right now.For pull requests, I lean strongly to requiring people to open a new one, as a year later there will likely be massive merge conflicts. As for issues...my personal preference is that people open a new one and link to the old issue (which I realize is an additional step). The reason for this is the issue - if returned to a year or more later - is likely to need a significant update to bring in all the context of the current time. Yes, that can be done on an existing issue...but it might work better to force a new issue. Will get back to you on this when I do some more research on the lock bot - I think it should be up to each team how they want to use it or something similar.

**Comment by kekaichinose** [comment]
@nellshamrell +1 on your perspective on Issues. Especially when they are a year or more out, it makes more sense to open a new one with a ref to the old one. In this way, there is context for the issue with respect to the current version of the product.

**Comment by nellshamrell** [comment]
I'd like to leave whether or not to use a lock bot up to each team - as it will vary with volume of issues received, etc.

**Comment by ramereth** [comment]
@nellshamrell I think it might be a good idea to add a section which explains when and why an issue/PR might be locked as you mentioned above. I've had that happen to me before and it would be good to have that here I think.

**Comment by nellshamrell** [comment]
Ah - that is an excellent point, @ramereth, I will add that in!

**Comment by nellshamrell** [comment]
Apologies for the delay on this - I have now added context around locking conversation on older issues and pull requests.

**Comment by miah** [comment]
Should we point to the support boundaries doc, or reference its included template for saying no?

**Comment by ramereth** [comment]
@nellshamrell thanks for doing that, I think you covered it well!

**Comment by miah** [comment]
We've been using this template while closing out older issues.

```
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
```

**Pull request merged**
